/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.entry.view.stats.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetEntryViewStats service. Represents a row in the &quot;AssetEntryViewStats&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.asset.entry.view.stats.model.impl.AssetEntryViewStatsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.asset.entry.view.stats.model.impl.AssetEntryViewStatsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntryViewStats
 * @see com.liferay.asset.entry.view.stats.model.impl.AssetEntryViewStatsImpl
 * @see com.liferay.asset.entry.view.stats.model.impl.AssetEntryViewStatsModelImpl
 * @generated
 */
@ProviderType
public interface AssetEntryViewStatsModel extends AttachedModel,
	BaseModel<AssetEntryViewStats>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset entry view stats model instance should use the {@link AssetEntryViewStats} interface instead.
	 */

	/**
	 * Returns the primary key of this asset entry view stats.
	 *
	 * @return the primary key of this asset entry view stats
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset entry view stats.
	 *
	 * @param primaryKey the primary key of this asset entry view stats
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the stats ID of this asset entry view stats.
	 *
	 * @return the stats ID of this asset entry view stats
	 */
	public long getStatsId();

	/**
	 * Sets the stats ID of this asset entry view stats.
	 *
	 * @param statsId the stats ID of this asset entry view stats
	 */
	public void setStatsId(long statsId);

	/**
	 * Returns the group ID of this asset entry view stats.
	 *
	 * @return the group ID of this asset entry view stats
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this asset entry view stats.
	 *
	 * @param groupId the group ID of this asset entry view stats
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this asset entry view stats.
	 *
	 * @return the company ID of this asset entry view stats
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this asset entry view stats.
	 *
	 * @param companyId the company ID of this asset entry view stats
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this asset entry view stats.
	 *
	 * @return the user ID of this asset entry view stats
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this asset entry view stats.
	 *
	 * @param userId the user ID of this asset entry view stats
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this asset entry view stats.
	 *
	 * @return the user uuid of this asset entry view stats
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this asset entry view stats.
	 *
	 * @param userUuid the user uuid of this asset entry view stats
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this asset entry view stats.
	 *
	 * @return the create date of this asset entry view stats
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset entry view stats.
	 *
	 * @param createDate the create date of this asset entry view stats
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the fully qualified class name of this asset entry view stats.
	 *
	 * @return the fully qualified class name of this asset entry view stats
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this asset entry view stats.
	 *
	 * @return the class name ID of this asset entry view stats
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this asset entry view stats.
	 *
	 * @param classNameId the class name ID of this asset entry view stats
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this asset entry view stats.
	 *
	 * @return the class p k of this asset entry view stats
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this asset entry view stats.
	 *
	 * @param classPK the class p k of this asset entry view stats
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the asset entry ID of this asset entry view stats.
	 *
	 * @return the asset entry ID of this asset entry view stats
	 */
	public long getAssetEntryId();

	/**
	 * Sets the asset entry ID of this asset entry view stats.
	 *
	 * @param assetEntryId the asset entry ID of this asset entry view stats
	 */
	public void setAssetEntryId(long assetEntryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetEntryViewStats assetEntryViewStats);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetEntryViewStats> toCacheModel();

	@Override
	public AssetEntryViewStats toEscapedModel();

	@Override
	public AssetEntryViewStats toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}