/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.asset.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetViewStats service. Represents a row in the &quot;AssetViewStats&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.asset.model.impl.AssetViewStatsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.asset.model.impl.AssetViewStatsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetViewStats
 * @see com.liferay.portlet.asset.model.impl.AssetViewStatsImpl
 * @see com.liferay.portlet.asset.model.impl.AssetViewStatsModelImpl
 * @generated
 */
@ProviderType
public interface AssetViewStatsModel extends AttachedModel,
	BaseModel<AssetViewStats> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset view stats model instance should use the {@link AssetViewStats} interface instead.
	 */

	/**
	 * Returns the primary key of this asset view stats.
	 *
	 * @return the primary key of this asset view stats
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset view stats.
	 *
	 * @param primaryKey the primary key of this asset view stats
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the view stats ID of this asset view stats.
	 *
	 * @return the view stats ID of this asset view stats
	 */
	public long getViewStatsId();

	/**
	 * Sets the view stats ID of this asset view stats.
	 *
	 * @param viewStatsId the view stats ID of this asset view stats
	 */
	public void setViewStatsId(long viewStatsId);

	/**
	 * Returns the user ID of this asset view stats.
	 *
	 * @return the user ID of this asset view stats
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this asset view stats.
	 *
	 * @param userId the user ID of this asset view stats
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this asset view stats.
	 *
	 * @return the user uuid of this asset view stats
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this asset view stats.
	 *
	 * @param userUuid the user uuid of this asset view stats
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the view date of this asset view stats.
	 *
	 * @return the view date of this asset view stats
	 */
	public Date getViewDate();

	/**
	 * Sets the view date of this asset view stats.
	 *
	 * @param viewDate the view date of this asset view stats
	 */
	public void setViewDate(Date viewDate);

	/**
	 * Returns the fully qualified class name of this asset view stats.
	 *
	 * @return the fully qualified class name of this asset view stats
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this asset view stats.
	 *
	 * @return the class name ID of this asset view stats
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this asset view stats.
	 *
	 * @param classNameId the class name ID of this asset view stats
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this asset view stats.
	 *
	 * @return the class p k of this asset view stats
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this asset view stats.
	 *
	 * @param classPK the class p k of this asset view stats
	 */
	@Override
	public void setClassPK(long classPK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetViewStats assetViewStats);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetViewStats> toCacheModel();

	@Override
	public AssetViewStats toEscapedModel();

	@Override
	public AssetViewStats toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}