/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.change.tracking.configuration;

/**
 * @author Mate Thurzo
 */
public interface ChangeTrackingConfigurationRegistrar<T, U> {

	/**
	 * Creates the change tracking configuration object using the given builder
	 *
	 * @param builder The builder object for a specific resource entity type and
	 *                version entity type
	 * @return The change tracking configuration object generated by the builder
	 */
	public ChangeTrackingConfiguration changeTrackingConfiguration(
		ChangeTrackingConfiguration.Builder<T, U> builder);

}